spring:
  redis:
    database: 0
    host: 127.0.0.1
    password:  
    port: 6379  
    pool: 
      max-idle: 32 
      min-idle: 2  # 连接池中的最小空闲连接  
      max-active: 32    # 连接池最大连接数（使用负值表示没有限制）  
      max-wait: 5000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      
    #这两个配置是redis集群时用的，如果没有集群加上会报找不到master错误
    #sentinel:
    #  master:   # name of Redis server 
    #  nodes:  # comma-separated list of host:port pairs 
